# API Keys
OPENAI_API_KEY = "sk-proj-mAEKMJs4macYWZdvR7li24RoJG2XG6qeHiC8jwkg9cYiiSXglujN8vLJTXYXIn90x0gZ32cWbHT3B1bkFJvDgOgUiwzf9QMCciGYs95lRgCtY0_5XfWMUvYyBD3j7kvR5nGrbAXyFfxIDkYaU5y3MaWSkEAA"
HUGGINGFACE_API_KEY = "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"

# Main file configuration
[server]
mainFile = "streamlit_app.py" 